package cli

import (
	"fmt"
	"net/url"
	"path"
	"sort"
	"strings"
)

// scaffoldFromCompose turns a real docker-compose.yml into a recipe directory.
//
// Everything it writes is a proposal. The proposals it is confident about - which
// service is the application, which directories hold state, which database is behind
// it, which port to probe - it writes as working YAML. Everything else becomes a TODO
// that names the decision. The result validates as it comes out, so the contributor's
// next command is about their application rather than about YAML.
func scaffoldFromCompose(name string, d *detected) (map[string]string, error) {
	if !recipeName.MatchString(name) {
		return nil, fmt.Errorf("recipe name %q: expected 3 to 40 lower-case letters, digits and hyphens", name)
	}
	return map[string]string{
		"recipe.yaml":  recipeFromCompose(name, d),
		"compose.yaml": composeFromDetected(name, d),
		"README.md":    readmeFromCompose(name, d),
	}, nil
}

func recipeFromCompose(name string, d *detected) string {
	var b strings.Builder
	t := title(name)

	fmt.Fprintf(&b, `apiVersion: restored/v1
kind: Recipe

# Generated by "restored recipe init --compose". Every TODO below is a decision this
# command could not make for you. Work through them, then run:
#
#     restored recipe test ./recipes/%s
#
# which is exactly what CI runs on your pull request.
`, name)
	for _, note := range d.Notes {
		for _, line := range wrapComment(note, 76) {
			fmt.Fprintf(&b, "# %s\n", line)
		}
	}

	fmt.Fprintf(&b, `
metadata:
  name: %s
  title: %s
  description: >
    Verifies that a %s backup restores: the application serves its own pages, and the
    data that was backed up is still in it. TODO: say what your checks actually prove.
  # Put your GitHub handle here. restored does not guess it.
  maintainers: []
  # TODO: the upstream project's URL.
  tags: []

vars:
  app_port: %d
`, name, t, t, d.AppPort)

	if d.DB != nil && d.DB.Kind == "postgres-dump" {
		fmt.Fprintf(&b, `  db_name: %s
  db_user: %s
  # Not a secret. This database exists for about ninety seconds on an internal network
  # with no published ports, and is destroyed with `+"`compose down -v`"+`.
  db_password: restored-throwaway
`, orDefault(d.DB.Name, name), orDefault(d.DB.User, name))
	}

	b.WriteString("\ninputs:\n")
	if len(d.Dirs) == 0 {
		fmt.Fprintf(&b, `  # TODO: no volume was found in your compose file, so there is nothing here to
  # restore. A recipe needs at least one input. Name the directory the application
  # keeps its state in.
  data:
    kind: dir
    title: The %s data directory
    description: >
      TODO: what this holds, and where it usually lives on the host.
    default_path: /srv/%s/data
    required: true
    mount:
      env: RESTORED_INPUT_data
      into: %s:/data
`, t, name, d.AppService)
	}
	for _, dir := range d.Dirs {
		fmt.Fprintf(&b, `  %s:
    kind: dir
    title: The %s directory
    description: >
      Mounted at %s in the %q service. TODO: say what it holds, and where a default
      install keeps it on the host.
    default_path: /srv/%s/%s
    required: true
    mount:
      env: RESTORED_INPUT_%s
      into: %s:%s
`, dir.Name, path.Base(dir.Container), dir.Container, dir.Service,
			name, dir.Name, dir.Name, dir.Service, dir.Container)
	}

	switch {
	case d.DB != nil && d.DB.Kind == "postgres-dump":
		fmt.Fprintf(&b, `  db:
    kind: postgres-dump
    title: The %s database dump
    description: >
      Plain SQL from pg_dump, or a custom-format dump from pg_dump -Fc. The format is
      detected from the file's magic bytes, not from its extension. TODO: say where
      your backup writes it.
    default_path: /srv/%s/db.sql
    required: true
    load:
      service: %s
      database: "{{ .vars.db_name }}"
      user: "{{ .vars.db_user }}"
      timeout: 5m
`, t, name, d.DB.Service)
	case d.DB != nil && d.DB.Kind == "sqlite":
		within, rel := sqliteWithin(d)
		fmt.Fprintf(&b, `  db:
    kind: sqlite
    title: The %s SQLite database
    description: >
      The database file itself. It is declared separately so the SQL checks have
      something to point at, and so a zero-byte database is reported as a restore
      failure instead of as a mysteriously empty application.
    default_path: /srv/%s/%s
`, t, name, rel)
		if within != "" {
			fmt.Fprintf(&b, "    within: %s           # it lives inside that input; not restored twice\n", within)
		}
		b.WriteString(`    required: true
    load:
      integrity_check: true
`)
	}

	fmt.Fprintf(&b, `
ready:
  - name: the application answers on the internal network
    kind: http
    # TODO: the cheapest endpoint that proves the application is serving rather than
    # merely listening. A health endpoint is ideal; the home page will do.
    url: http://%s:{{ .vars.app_port }}/
    expect_status: 200
    timeout: 180s
    interval: 3s
`, d.AppService)
	if d.DB != nil && d.DB.Kind == "postgres-dump" {
		fmt.Fprintf(&b, `
  - name: postgres accepts connections
    kind: exec
    service: %s
    command: ["pg_isready", "-U", "{{ .vars.db_user }}", "-d", "{{ .vars.db_name }}"]
    timeout: 90s
    interval: 2s
`, d.DB.Service)
	}

	fmt.Fprintf(&b, `
checks:
  # The first two checks are NOT data-sensitive: both pass against an empty
  # application. `+"`restored recipe test`"+` rejects a recipe that has only checks like
  # these, because they manufacture confidence rather than earning it.
  - id: app-answers
    title: The application serves its home page
    kind: http
    url: http://%s:{{ .vars.app_port }}/
    expect:
      status: 200

  - id: data-dir-present
    title: The data directory survived the restore
    kind: file
    service: %s
    path: %s
    expect:
      exists: true
      is_dir: true
`, d.AppService, dirServiceOr(d, d.AppService), dirPathOr(d, "/data"))

	switch {
	case d.DB != nil && d.DB.Kind == "postgres-dump":
		fmt.Fprintf(&b, `
  # TODO: THIS is the check that makes the recipe worth anything. Replace the table
  # name with one that only a real installation has rows in - a user table, a document
  # table, whatever your application's data actually is.
  - id: rows-present
    title: The database contains at least one real row
    kind: sql
    driver: postgres
    service: %s
    database: "{{ .vars.db_name }}"
    user: "{{ .vars.db_user }}"
    query: "SELECT count(*) FROM todo_replace_this_table;"
    expect:
      scalar_int_min: 1
`, d.DB.Service)
	case d.DB != nil && d.DB.Kind == "sqlite":
		b.WriteString(`
  - id: db-integrity
    title: The SQLite database passes PRAGMA integrity_check
    kind: sql
    driver: sqlite
    file: "{{ .inputs.db.path }}"
    query: "PRAGMA integrity_check;"
    expect:
      scalar_equals: "ok"

  # TODO: THIS is the check that makes the recipe worth anything. Replace the table
  # name with one that only a real installation has rows in.
  - id: rows-present
    title: The database contains at least one real row
    kind: sql
    driver: sqlite
    file: "{{ .inputs.db.path }}"
    query: "SELECT count(*) FROM todo_replace_this_table;"
    expect:
      scalar_int_min: 1
`)
	default:
		b.WriteString(`
  # TODO: add a check that FAILS against an empty application. Without one this recipe
  # proves nothing, and ` + "`restored recipe test`" + ` will say so and refuse it.
`)
	}

	b.WriteString(`
test:
  # The round-trip harness runs these against a fresh, empty stack: seed creates data
  # the way a user would, export writes out what a backup would have taken. Then the
  # harness backs that up, restores it, and runs the checks above.
  seed:
    # TODO: create something the checks above can find. Prefer the application's own
    # API or CLI over writing to its database: a recipe that seeds through the front
    # door proves the restore end to end.
    []
  export:
`)
	if d.DB != nil && d.DB.Kind == "postgres-dump" {
		fmt.Fprintf(&b, `    # $RESTORED_EXPORT is mounted into every service by the harness, and only by the
    # harness. It does not exist during `+"`restored check`"+`.
    - name: dump the database into the staging tree
      kind: exec
      service: %s
      command:
        - sh
        - -c
        - 'pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" > "$RESTORED_EXPORT/db.sql"'
      timeout: 5m
      produces: db
`, d.DB.Service)
	} else {
		b.WriteString(`    # Every dir input is exported automatically, by copying it back out of the
    # container that owns it. Only an input the application has to serialise for
    # itself - a database dump - needs a step here.
    []
`)
	}
	return b.String()
}

func composeFromDetected(name string, d *detected) string {
	var b strings.Builder
	b.WriteString(`# Generated by "restored recipe init --compose", from your compose file.
#
# Four things were changed, and they are not negotiable: published ports are gone
# (restored publishes nothing and reaches the app from a helper container on the run's
# internal network), host bind mounts became ${RESTORED_INPUT_*}, the network is
# internal, and anything that referenced an environment variable of yours became a
# literal, because restored defines only ${RESTORED_VAR_*}, ${RESTORED_INPUT_*},
# ${RESTORED_TEST_ASSETS}, ${RESTORED_EXPORT} and ${RESTORED_RUN_ID}.
#
# Two things were ADDED, and you probably need them. The harness starts every service
# at once, so an application that treats a refused first database connection as fatal
# exits before the database is listening - and then the ready probe spends its whole
# budget failing to resolve a container that is no longer there. So: a healthcheck on
# the database, and a depends_on condition on the application. Keep both.
#
# Do not add ports:, privileged:, network_mode:, pid:, ipc:, or a bind mount to any
# path outside the workspace. ` + "`restored recipe validate`" + ` rejects all of them.
services:
`)

	order := serviceOrder(d)
	for _, svc := range order {
		fmt.Fprintf(&b, "  %s:\n", svc)
		fmt.Fprintf(&b, "    image: %s\n", pinned(d.imageOf(svc)))
		writeServiceEnv(&b, d, svc)
		writeServiceVolumes(&b, d, svc)
		writeServiceOrdering(&b, d, svc)
		b.WriteString("    networks: [restored]\n\n")
	}

	if d.DB != nil && d.DB.Kind == "postgres-dump" {
		b.WriteString("volumes:\n  db-data:\n\n")
	}
	b.WriteString(`networks:
  restored:
    internal: true
`)
	return b.String()
}

func writeServiceEnv(b *strings.Builder, d *detected, svc string) {
	env := d.envOf(svc)
	if d.DB != nil && d.DB.Kind == "postgres-dump" && svc == d.DB.Service {
		b.WriteString(`    environment:
      POSTGRES_DB: ${RESTORED_VAR_db_name}
      POSTGRES_USER: ${RESTORED_VAR_db_user}
      POSTGRES_PASSWORD: ${RESTORED_VAR_db_password}
`)
		return
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	if len(keys) == 0 {
		fmt.Fprintf(b, "    # TODO: whatever %q needs in order to start without its usual host.\n", svc)
		return
	}
	b.WriteString("    environment:\n")
	for _, k := range keys {
		value, changed := literalEnv(env[k])
		if changed {
			// The original text goes into the comment with its dollar signs removed:
			// restored scans the whole file for placeholders, comments included, and
			// would reject the file for merely mentioning one.
			fmt.Fprintf(b, "      # TODO: this was %s in your compose file.\n",
				strings.ReplaceAll(env[k], "$", ""))
		}
		// A connection string still pointing at the credentials this file has just
		// stopped using is a stack that cannot come up. See FC-04.
		if rewritten, ok := rewriteDBURL(value, d.DB); ok {
			b.WriteString("      # Repointed at the throwaway credentials this recipe mints, which are not\n" +
				"      # the ones your compose file used.\n")
			value = rewritten
		}
		fmt.Fprintf(b, "      %s: %s\n", k, quoteYAML(value))
	}
}

func writeServiceVolumes(b *strings.Builder, d *detected, svc string) {
	var lines []string
	for _, dir := range d.Dirs {
		if dir.Service == svc {
			lines = append(lines, fmt.Sprintf("      - ${RESTORED_INPUT_%s}:%s", dir.Name, dir.Container))
		}
	}
	if d.DB != nil && d.DB.Kind == "postgres-dump" && svc == d.DB.Service {
		// The database's own data directory is a throwaway named volume: the restore
		// arrives as a dump and is loaded into a database this run created.
		lines = append(lines, "      - db-data:/var/lib/postgresql/data")
	}
	if len(lines) == 0 {
		return
	}
	b.WriteString("    volumes:\n")
	b.WriteString(strings.Join(lines, "\n") + "\n")
}

// literalEnv strips a reference to the operator's own environment. A recipe runs on a
// stranger's machine, where ${DB_PASSWORD} is not set, and an unset variable silently
// expanding to the empty string is how a mount becomes "/".
func literalEnv(v string) (string, bool) {
	if !strings.Contains(v, "$") {
		return v, false
	}
	return "TODO-replace-me", true
}

// pinned flags an image reference with no tag, which --strict rejects and which makes
// a recipe stop reproducing the moment upstream moves.
func pinned(image string) string {
	if image == "" {
		return "TODO/replace-me:1.0.0   # TODO: no image was found for this service"
	}
	if !strings.Contains(image, ":") && !strings.Contains(image, "@") {
		return image + ":TODO   # TODO: pin a tag; an untagged image is not reproducible"
	}
	// `:latest` is rejected by the safety schema, and most real compose files use it,
	// so passing it through made the scaffold emit a recipe that failed the very next
	// command the scaffold told the contributor to run. See MNT-10 and FC-07.
	if strings.HasSuffix(image, ":latest") {
		return strings.TrimSuffix(image, ":latest") +
			":TODO   # TODO: your compose file said :latest. Pin the version you actually run"
	}
	return image
}

func quoteYAML(s string) string {
	if s == "" {
		return `""`
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

// serviceOrder puts the application first, then the database, then the rest: the
// order somebody reads the file in.
func serviceOrder(d *detected) []string {
	seen := map[string]bool{}
	var out []string
	add := func(s string) {
		if s != "" && !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	add(d.AppService)
	if d.DB != nil {
		add(d.DB.Service)
	}
	for _, s := range d.Services {
		add(s)
	}
	return out
}

func readmeFromCompose(name string, d *detected) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\nWhat this recipe assumes about your backup.\n\n## Inputs\n\n", title(name))
	b.WriteString("| input | what it is | where it usually lives |\n|---|---|---|\n")
	for _, dir := range d.Dirs {
		fmt.Fprintf(&b, "| `%s` | %s in the `%s` container | `/srv/%s/%s` |\n",
			dir.Name, dir.Container, dir.Service, name, dir.Name)
	}
	if d.DB != nil {
		switch d.DB.Kind {
		case "postgres-dump":
			fmt.Fprintf(&b, "| `db` | a pg_dump of the `%s` database | `/srv/%s/db.sql` |\n", d.DB.Service, name)
		case "sqlite":
			_, rel := sqliteWithin(d)
			fmt.Fprintf(&b, "| `db` | the SQLite database | `/srv/%s/%s` |\n", name, rel)
		}
	}
	fmt.Fprintf(&b, `
If your paths differ, point the inputs at yours:

    restored check --recipe ./recipes/%s --input %s=/your/path

## Mapping a typical install

TODO: name the two or three ways this application is usually deployed, and what each
one means for the paths above. A contributor reading this should be able to answer
"where is my data?" without opening the application.

## What the checks prove

TODO: replace this section with the answer to one question: **which of these checks
would fail if the backup were empty?** If the answer is "none", the recipe is not
finished, and `+"`restored recipe test`"+` will say so.
`, name, firstInputName(d))

	if len(d.Notes) > 0 {
		b.WriteString("\n## What `recipe init` could not work out\n\n")
		for _, note := range d.Notes {
			fmt.Fprintf(&b, "- %s\n", note)
		}
	}
	return b.String()
}

// ---- small accessors -------------------------------------------------------

func (d *detected) imageOf(svc string) string {
	if svc == d.AppService {
		return d.AppImage
	}
	return d.images[svc]
}

func (d *detected) envOf(svc string) map[string]string { return d.envs[svc] }

func dirServiceOr(d *detected, fallback string) string {
	if len(d.Dirs) > 0 {
		return d.Dirs[0].Service
	}
	return fallback
}

func dirPathOr(d *detected, fallback string) string {
	if len(d.Dirs) > 0 {
		return d.Dirs[0].Container
	}
	return fallback
}

func firstInputName(d *detected) string {
	if len(d.Dirs) > 0 {
		return d.Dirs[0].Name
	}
	return "data"
}

// sqliteWithin locates the database file relative to whichever dir input contains it,
// so the same bytes are not restored twice.
func sqliteWithin(d *detected) (within, rel string) {
	if d.DB == nil || d.DB.File == "" {
		return "", "data/app.db"
	}
	for _, dir := range d.Dirs {
		prefix := strings.TrimSuffix(dir.Container, "/") + "/"
		if strings.HasPrefix(d.DB.File, prefix) {
			return dir.Name, dir.Name + "/" + strings.TrimPrefix(d.DB.File, prefix)
		}
	}
	return "", strings.TrimPrefix(d.DB.File, "/")
}

func orDefault(v, fallback string) string {
	if v == "" {
		return fallback
	}
	return v
}

// wrapComment breaks a note into comment-width lines.
func wrapComment(s string, w int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return nil
	}
	var lines []string
	line := words[0]
	for _, word := range words[1:] {
		if len(line)+1+len(word) > w {
			lines = append(lines, line)
			line = word
			continue
		}
		line += " " + word
	}
	return append(lines, line)
}

// writeServiceOrdering emits the healthcheck on the database and the depends_on edge
// on the application.
//
// The harness starts every service at once. An application that treats a refused
// first database connection as fatal - which is most of them - exits before the
// database is listening, and because the container is then gone, Docker's embedded
// DNS has nothing to resolve and the ready probe reports "Could not resolve host" for
// the whole of its budget. The real cause, `connection refused`, appears only under
// --log-level debug.
//
// The scaffold used to drop both keys when it found them in the contributor's file,
// which cost the session 4 fresh-clone reviewer two blind three-minute runs. They are
// synthesised rather than copied, because a contributor's own healthcheck usually
// references credentials this file has just stopped using.
// See docs/review/fresh-clone.md FC-03.
func writeServiceOrdering(b *strings.Builder, d *detected, svc string) {
	if d.DB == nil || d.DB.Kind != "postgres-dump" || d.DB.Service == "" {
		return
	}
	if svc == d.DB.Service {
		b.WriteString(`    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${RESTORED_VAR_db_user} -d ${RESTORED_VAR_db_name}"]
      interval: 2s
      timeout: 3s
      retries: 30
`)
		return
	}
	if svc == d.AppService {
		fmt.Fprintf(b, `    depends_on:
      %s:
        condition: service_healthy
`, d.DB.Service)
	}
}

// rewriteDBURL points a connection string at the credentials this file actually uses.
//
// The scaffold rewrites the database service's own POSTGRES_* variables to
// ${RESTORED_VAR_*} and used to leave the application's DATABASE_URL frozen at
// whatever the contributor's file said - so the two halves of the generated file
// disagreed about the password and the stack could not come up. That was not a
// decision the scaffold flagged as a TODO; it was one it silently got wrong.
//
// The rewrite is deliberately narrow: only a URL whose host is the database service,
// and only its user, password and database name. See docs/review/fresh-clone.md FC-04.
func rewriteDBURL(value string, db *detectedDB) (string, bool) {
	if db == nil || db.Kind != "postgres-dump" || db.Service == "" {
		return value, false
	}
	u, err := url.Parse(strings.TrimSpace(value))
	if err != nil || u.Scheme == "" || u.Host == "" {
		return value, false
	}
	if u.Hostname() != db.Service {
		return value, false
	}
	if u.User == nil {
		return value, false
	}
	rewritten := fmt.Sprintf("%s://${RESTORED_VAR_db_user}:${RESTORED_VAR_db_password}@%s/${RESTORED_VAR_db_name}",
		u.Scheme, u.Host)
	if u.RawQuery != "" {
		rewritten += "?" + u.RawQuery
	}
	return rewritten, rewritten != value
}
